version: "3.8"

services:
  frontend:
    build:
      context: ./client
      dockerfile: ../frontend.dockerfile  
    ports:
      - "80:80"
    networks:
      - frontend_network
  
  backend:
    build:
      context: ./server
      dockerfile: ../backend.dockerfile  
    ports:
      - "5000:5000"
    networks:
      - frontend_network 

networks:
  frontend_network:
    driver: bridge
